php-fpm:
    build: docker/php-fpm
    ports:
        - 9000:9000
    volumes:
        - ./:/var/www/html/
    links:
        - db

nginx:
    build: docker/nginx
    ports:
        - 8080:80
    volumes:
        - ./:/var/www/html/
    links:
        - php-fpm

db:
    image: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_DATABASE: zharman
        MYSQL_USER: zharman
        MYSQL_PASSWORD: zharman
        MYSQL_ROOT_PASSWORD: zharman
