const Icon = ({ className, figure, size }) => (
  <i class={ `mark-icon icon-${size} ${className}` }>
    <span class={ className }>{ ICONS[figure] }</span></i>
);

const ICONS = {
  // TODO: Add these icons
  // 🕒🝎👁👽🐦🐕🐈🎭🏷𐄹⛑❌⬠➹✨♀♂❄❆
  // ⛽✆☑☒☎🏭🏝☄☖☗🏛🏞🏙☔🏘🏗🏔🏋🏄🎧🎞🎟🎖
  // 🎓🍽🐵👁💣💰💳💻💹📚🕊🕴🕷🕸🖼🗑🗓🗝🗡🗨🗺
  // 🚍🚔🚘🚭🚲🚹🚺👪🚼🛋🛎🛍🛠🛡🛢🛤🛳
  anchor: '⚓',
  atom: '⚛',
  ballot: '྾',
  beach: '⛱',
  biohazard: '☣',
  boat: '⛵',
  check: '✓',
  chili: '🌶',
  chore: '⚙',
  church: '⛪',
  circle: '◯',
  closed: '⛔',
  cloud: '☁',
  cloudy: '⛅',
  coffee: '☕',
  diamond: '◇',
  eject: '⏏',
  eyeGlass: '👓',
  ferry: '⛴',
  globeAfrica: '🌍',
  globeAmerica: '🌎',
  globeAustralia: '🌏',
  hammer: '⚒',
  health: '☤',
  hearth: '❤',
  helm: '⎈',
  hexagon: '⎔',
  home: '🏠',
  hourglass: '⌛',
  hourglass2: '⏳',
  inbox: '📥',
  film: '🎬',
  flag: '⚑',
  fog: '🌫',
  link: '☍',
  lock: '🔒',
  mailbox: '📭',
  note: '♫',
  outbox: '📤',
  pause: '⏸',
  peace: '☮',
  pencil: '✎',
  pick: '⛏',
  radioactive: '☢',
  ray: '⚡',
  record: '⏺',
  recycle: '♻',
  tent: '⛺',
  triangle: '△',
  scales: '⚖',
  search: '🔍',
  skull: '☠',
  snowman: '⛄',
  speaker: '🔈',
  speakerDisable: '🔇',
  speakerSound: '🔉',
  stop: '⏹',
  spinner: '⚙',
  star: '★',
  storm: '🌧',
  sun: '☀',
  sun2: '☼',
  swim: '🏊',
  swords: '⚔',
  temperature: '🌡',
  thunder: '🌩',
  thunderstorm: '⛈',
  tornado: '🌪',
  trophy: '🏆',
  umbrella: '☂',
  unlock: '🔓',
  videoGame: '🎮',
  warning: '⚠',
  wheelchair: '♿'
};

export default Icon;
