const ICONS = {
  anchor: '⚓',
  atom: '⚛',
  ballot: '྾',
  beach: '⛱',
  biohazard: '☣',
  boat: '⛵',
  check: '✓',
  chevronDown: '⏷',
  chevronLeft: '⏴',
  chevronRight: '⏵',
  chevronUp: '⏶',
  chili: '🌶',
  chore: '⚙',
  church: '⛪',
  circle: '◯',
  closed: '⛔',
  cloud: '☁',
  cloudy: '⛅',
  coffee: '☕',
  diamond: '◇',
  eject: '⏏',
  eyeGlass: '👓',
  ferry: '⛴',
  globeAfrica: '🌍',
  globeAmerica: '🌎',
  globeAustralia: '🌏',
  hammer: '⚒',
  health: '☤',
  hearth: '❤',
  helm: '⎈',
  hexagon: '⎔',
  hourglass: '⌛',
  hourglass2: '⏳',
  house: '🏠',
  inbox: '📥',
  film: '🎬',
  flag: '⚑',
  fog: '🌫',
  link: '☍',
  lock: '🔒',
  mailbox: '📭',
  note: '♫',
  outbox: '📤',
  pause: '⏸',
  peace: '☮',
  pencil: '✎',
  pick: '⛏',
  powerOn: '⏻',
  powerOff: '⏼',
  powerSleep: '⏾',
  radioactive: '☢',
  ray: '⚡',
  record: '⏺',
  recycle: '♻',
  road: '⛗',
  tent: '⛺',
  triangle: '△',
  truck: '⛟',
  scales: '⚖',
  search: '🔍',
  shield: '⛨',
  skull: '☠',
  snowman: '⛄',
  speaker: '🔈',
  speakerDisable: '🔇',
  speakerSound: '🔉',
  stop: '⏹',
  spinner: '🗘',
  square: '☐',
  star: '★',
  storm: '🌧',
  sun: '☀',
  sun2: '☼',
  swim: '🏊',
  swords: '⚔',
  temperature: '🌡',
  thunder: '🌩',
  thunderstorm: '⛈',
  tornado: '🌪',
  trophy: '🏆',
  unlock: '🔓',
  videoGame: '🎮',
  warning: '⚠',
  water: '🌢',
  wheelchair: '♿'
};

const Icon = ({ className, figure, size }) => (
  <i class={ `mark-icon icon-${size} ${className}` }>
    <span class={ className }>{ ICONS[figure] }</span></i>
);

export default Icon;
